# Generated by Django 5.0.6 on 2024-06-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloomFilterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=1000)),
                ('num_hashes', models.IntegerField(default=15)),
                ('bit_array', models.BinaryField(null=True)),
            ],
        ),
    ]
