# Generated by Django 5.0.6 on 2024-06-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomfilter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloomfiltermodel',
            name='num_hashes',
        ),
        migrations.RemoveField(
            model_name='bloomfiltermodel',
            name='size',
        ),
    ]
